add Test for running shared object macro
root-project/roottest pull request #1104
Opened 2024-04-05 08:26 UTC by ferdymercury

matches https://github.com/root-project/root/pull/14813

2024-04-05 11:31 UTC, dpiparo commented
Thanks for this PR, this is great. We need to impose a dependency between the two tests though, as CTest will try to run them in parallel. We can express the dependency in CMake, or write a simple shell/python script that 
1. writes the hello.C macro to disk
2. Builds the library with aclic
3. runs the library as a macro
4. cleans up the space

This latter solution has the advantage of being self contained in 1 single simple file.
What do you think?

2024-04-05 13:01 UTC, ferdymercury commented
> Thanks for this PR, this is great. We need to impose a dependency between the two tests though, as CTest will try to run them in parallel. We can express the dependency in CMake, or write a simple shell/python script that
> 
>     1. writes the hello.C macro to disk
> 
>     2. Builds the library with aclic
> 
>     3. runs the library as a macro
> 
>     4. cleans up the space
> 
> 
> This latter solution has the advantage of being self contained in 1 single simple file. What do you think?

Done. Not sure though whether the working_directory and outcnv variables should be like this or not.

2024-04-05 16:45 UTC, ferdymercury commented
> Done. Not sure though whether the working_directory and outcnv variables should be like this or not.

Solved now!

2024-04-05 16:49 UTC, dpiparo approved these changes

2024-04-05 18:13 UTC, pcanal commented on root/meta/hello_ROOT.sh
> +#! /bin/sh
Actually the feature pre-dates the use of FIXTURE and the example we have (see root/io/stdpair for example)
use `ROOTTEST_COMPILE_MACRO` and `${COMPILE_MACRO_TEST}`

2024-04-05 18:13 UTC, pcanal requested changes
Let's replace the shell script.

2024-04-06 08:50 UTC, ferdymercury commented on root/meta/hello_ROOT.sh
> +#! /bin/sh
Fixed as suggested

2024-04-06 09:38 UTC, ferdymercury commented
It's not able to find the compiled macro. Is it stored in a different directory the result maybe?

2024-04-06 14:15 UTC, ferdymercury commented
> It's not able to find the compiled macro. Is it stored in a different directory the result maybe?

Ok, I think it's solved now!

2024-04-08 07:12 UTC, guitargeek commented
Thanks! For tests we don't necessarily need backports, by the way. As long as one branch tests the features it's good!

2024-04-08 07:12 UTC, guitargeek approved these changes

2024-04-08 07:14 UTC, merged