[PyROOT] Add test for using function decl
root-project/roottest pull request #595
Opened 2020-09-15 07:56 UTC by stwunsch

Reported on mattermost that "import ROOT; ROOT.TGraphMultiErrors().SetLineColor(0)"
breaks with 6.22 and is not fixed in master due to the ROOT PR #6277.

2020-09-15 08:45 UTC, stwunsch commented
@etejedor Is this the correct place for the test?

2020-09-22 07:42 UTC, etejedor requested changes
Thanks @stwunsch ! I wonder if we could create a new class of tests for using declarations here:

https://github.com/root-project/roottest/blob/master/python/cpp/PyROOT_cpptests.py

since this is likely not the only test we will want to add for using declarations (there are several tickets related to it).

2020-09-22 08:51 UTC, stwunsch commented
> Thanks @stwunsch ! I wonder if we could create a new class of tests for using declarations here:
> 
> https://github.com/root-project/roottest/blob/master/python/cpp/PyROOT_cpptests.py
> 
> since this is likely not the only test we will want to add for using declarations (there are several tickets related to it).

I've moved the test and introduced a new class of tests related to using declarations!

2020-09-22 09:33 UTC, etejedor approved these changes

2020-09-22 12:09 UTC, merged