fix tExecutor test on Windows
root-project/roottest pull request #637
Opened 2021-01-14 15:15 UTC by xvallspl

2021-01-14 15:16 UTC, xvallspl commented
@bellenot Would this be enough? to deal with https://github.com/root-project/roottest/pull/636

2021-01-14 15:55 UTC, bellenot commented
> @bellenot Would this be enough? to deal with #636

I think so (it's exactly what I wanted to try). I'll approve it as soon as I managed to successfully run it on Windows

2021-01-14 16:38 UTC, bellenot commented on root/multicore/CMakeLists.txt
> +if(NOT MSVC OR win_broken_tests)
``

2021-01-14 16:54 UTC, bellenot requested changes
In general `_MSC_VER` is preferred over `R__WIN32` which can also be defined when using different compilers supporting more features than MSVC

2021-01-14 16:54 UTC, bellenot commented on root/multicore/tExecutor.cxx
> +#ifndef R__WIN32
```suggestion
#ifndef _MSC_VER
```

2021-01-14 16:54 UTC, bellenot commented on root/multicore/tExecutor.cxx
> +#ifndef R__WIN32
```suggestion
#ifndef _MSC_VER
```

2021-01-15 10:11 UTC, bellenot approved these changes
Thanks!

2021-01-15 13:32 UTC, merged