Fix a missing include.
root-project/roottest pull request #930
Opened 2022-12-27 17:17 UTC by hageboeck

For an unknown reason, cling managed to compile a test that's missing an include directive. The include is added here, since it provoked a failure in a branch that's still WIP.

2022-12-27 17:20 UTC, guitargeek approved these changes
Thank you very much!

2023-01-18 08:58 UTC, hahnjo commented
@phsft-bot build

2023-01-18 09:34 UTC, Axel-Naumann commented
That should be autoloaded, I believe? It's not compiled but interpreted, so autoloading is part of the game.

2023-03-23 12:22 UTC, hageboeck commented
@phsft-bot build

2023-04-30 10:04 UTC, Axel-Naumann commented
@phsft-bot build

2023-04-30 19:12 UTC, pcanal commented
All the error seems to be due to a 'missing' rebase of roottest and are unrelated to the change here.

2025-03-30 20:49 UTC, guitargeek requested changes
@hageboeck, probably this is not needed anymore?

2025-03-31 09:44 UTC, hageboeck commented
I don't think so. Let's close it.

2025-03-31 09:44 UTC, closed without merging